config/routes.rb
ViveStore::Application.routes.draw do

  devise_for :users

  resources :users do
    resources :carts
  end

  resources :stores, only: [:show] do
    resources :products do
      member do
        post 'add_cart'
      end
    end
    member do
      get 'story'
    end
  end

  namespace :admin do
    get '' => 'home#index', as: :home
    resources :reports
    resources :products
    resources :orders
    resources :shippments
    resources :payments
    resources :stores, except: [:index]
  end

  match '', to: 'stores#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  root :to => 'home#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :amount, :number
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to admin_order_path(@order), notice: 'Order was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to admin_order_path(@order), notice: 'Order was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to admin_orders_url }
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @orders }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/views/admin/orders/_form.html.haml
= form_for @order, url: @order.new_record? ? admin_orders_path : admin_order_path(@order), :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :number, :class => 'control-label'
    .controls
      = f.text_field :number, :class => 'text_field'
  .control-group
    = f.label :amount, :class => 'control-label'
    .controls
      = f.text_field :amount, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_orders_path, :class => 'btn'

app/views/admin/orders/edit.html.haml
- model_class = Order
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/orders/index.html.haml
- model_class = Order
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:number)
      %th= model_class.human_attribute_name(:amount)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @orders.each do |order|
      %tr
        %td= link_to order.id, admin_order_path(order)
        %td= order.number
        %td= order.amount
        %td=l order.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_order_path(order), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_order_path(order), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_admin_order_path, :class => 'btn btn-primary'

app/views/admin/orders/new.html.haml
- model_class = Order
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/orders/show.html.haml
- model_class = Order
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:number) + ':'
  %br
  = @order.number
%p
  %strong= model_class.human_attribute_name(:amount) + ':'
  %br
  = @order.amount

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_orders_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_order_path(@order), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_order_path(@order), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'