config/routes.rb
ViveStore::Application.routes.draw do

  devise_for :users

  resources :users do
    resources :carts
  end

  resources :stores, only: [:show] do
    resources :products do
      member do
        post 'add_cart'
      end
    end
    member do
      get 'story'
    end
  end

  namespace :admin do
    get '' => 'home#index', as: :home
    resources :reports
    resources :products
    resources :orders
    resources :shippments
    resources :payments
    resources :stores, except: [:index]
  end

  match '', to: 'stores#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  root :to => 'home#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :title, :user_id, :store_id, :product_id
  belongs_to :user
  belongs_to :product

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!
  # GET /carts
  # GET /carts.json
  def index
    @products = current_user.cart_products
    @store = current_user.store

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy

    respond_to do |format|
      format.html { redirect_to carts_url }
      format.json { head :no_content }
    end
  end
end

app/views/carts/_form.html.haml
= form_for @cart, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), carts_path, :class => 'btn'

app/views/carts/edit.html.haml
- model_class = Cart
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/carts/index.html.haml
- model_class = Product
.page-header
  %h1 Cart
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.id, store_product_path(@store, product)
        %td= product.title
        %td= product.description
        %td=l product.created_at
        %td
          = link_to 'Delete', user_cart_path(current_user, product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to 'Shippment', '', :class => 'btn btn-primary'
= link_to 'Payment', '', :class => 'btn btn-primary'

app/views/carts/new.html.haml
- model_class = Cart
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/carts/show.html.haml
- model_class = Cart
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @cart.title

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), carts_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_cart_path(@cart), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), cart_path(@cart), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'