config/routes.rb
ViveStore::Application.routes.draw do

  devise_for :users

  resources :users do
    resources :carts
  end

  resources :stores, only: [:show] do
    resources :products do
      member do
        post 'add_cart'
      end
    end
    member do
      get 'story'
    end
  end

  namespace :admin do
    get '' => 'home#index', as: :home
    resources :reports
    resources :products
    resources :orders
    resources :shippments
    resources :payments
    resources :stores, except: [:index]
  end

  match '', to: 'stores#show', constraints: lambda { |r| r.subdomain.present? && r.subdomain != 'www' }

  root :to => 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :title, :store_id
  belongs_to :store
  belongs_to :user


end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  load_and_authorize_resource
  before_filter :authenticate_user!

  def index
    @products = current_user.products

    respond_to do |format|
      format.html
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = current_user.products.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = current_user.products.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = current_user.products.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = current_user.products.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to admin_product_path(@product), notice: 'Product was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = current_user.products.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to admin_products_path }
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource except: [:show]
  before_filter :authenticate_user!, except: [:show]
  before_filter :find_store
  # GET /products
  # GET /products.json
  def index
    @products = @store.products

    respond_to do |format|
      format.html { render layout: 'fix_template'}
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = @store.products.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  def add_cart
    @product = @store.products.find(params[:id])
    current_user.cart_products << @product
    respond_to do |format|
      format.js
    end
  end

  private

  def find_store
    @store = Store.find_by_id(params[:store_id])||Store.find_by_permalink(params[:store_id])
  end

end

app/views/admin/products/_form.html.haml
= form_for @product, url: (@product.new_record? ? admin_products_path : admin_product_path(@product)), :html => { :class => 'form-horizontal' } do |f|
  = f.hidden_field :store_id
  .control-group
    = f.label :title, :class => 'control-label'
    .controls
      = f.text_field :title, :class => 'text_field'
  .control-group
    = f.label :description, :class => 'control-label'
    .controls
      = f.text_area :description, :class => 'text_area'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), admin_products_path, :class => 'btn'

app/views/admin/products/edit.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/products/index.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @products.each do |product|
      %tr
        %td= link_to product.id, admin_product_path(product)
        %td= product.title
        %td= product.description
        %td=l product.created_at
        %td
          = link_to 'Edit', edit_admin_product_path(product), :class => 'btn btn-mini'
          = link_to 'Delete', admin_product_path(product), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to 'New', new_admin_product_path, :class => 'btn btn-primary'

app/views/admin/products/new.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/admin/products/show.html.haml
- model_class = Product
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @product.title
%p
  %strong= model_class.human_attribute_name(:description) + ':'
  %br
  = @product.description

.form-actions
  = link_to 'ALL', admin_products_path, :class => 'btn'
  = link_to 'Edit', edit_admin_product_path(@product), :class => 'btn'
  = link_to 'Delete', admin_product_path(@product), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'